openapi: 3.0.3
info:
  title: Beer Dispenser API
  version: 1.0.0
paths:
  api/dispenser:
    get:
      summary: Retrieve all dispensers
      responses:
        '200':
          description: A list of all available dispensers
          content:
            application/json:
              example:
                - id: 1
                  flow_volume: 0.05
                  price: 1.5
                  status: closed
                - id: 2
                  flow_volume: 0.03
                  price: 2.0
                  status: open
    post:
      summary: Create a new dispenser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dispenser'
      responses:
        '201':
          description: Dispenser created successfully
          content:
              application/json:
                example:
                  id: 3
                  flow_volume: 0.04
                  price: 1.8

  api/dispenser/{dispenser_id}:
    get:
      summary: Retrieve information about a dispenser
      parameters:
        - in: path
          name: dispenser_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Dispenser information
          content:
            application/json:
              example:
                id: 1
                flow_volume: 0.05
                price: 1.5
                status: closed
  api/dispenser/{dispenser_id}/open:
    post:
      summary: Open a dispenser
      parameters:
        - in: path
          name: dispenser_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Dispenser opened successfully
  api/dispenser/{dispenser_id}/close:
    post:
      summary: Close a dispenser
      parameters:
        - in: path
          name: dispenser_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Dispenser closed successfully
          content:
            application/json:
              example:
                amount: 0.5
                cost: 2.5
  api/statistics/:
    get:
      summary: Retrieve statistics for all dispenser
      responses:
        '200':
          description: Dispenser statistics (all)
          content:
            application/json:
              example:
                - dispenser_id: 1
                  flow_volume: 0.05
                  price: 1.5
                  is_open: false
                  total_transactions: 5
                  total_amount: 2.5
                  total_revenue: 3.75
                  transactions:
                    - transaction_id: 1
                      amount: 0.7
                      revenue: 1.05
                      start_time: "2023-07-14T10:00:00Z"
                      end_time: "2023-07-14T10:10:00Z"
                    - transaction_id: 2
                      amount: 0.8
                      revenue: 1.6
                      start_time: "2023-07-14T11:00:00Z"
                      end_time: "2023-07-14T11:05:00Z"
                    - transaction_id: 3
                      amount: 0.6
                      revenue: 1.2
                      start_time: "2023-07-14T12:00:00Z"
                      end_time: "2023-07-14T12:02:00Z"
                - dispenser_id: 2
                  flow_volume: 0.03
                  price: 2.0
                  is_open: true
                  total_transactions: 3
                  total_amount: 1.9
                  total_revenue: 3.8
                  transactions:
                    - transaction_id: 1
                      amount: 0.5
                      revenue: 1.0
                      start_time: "2023-07-14T09:00:00Z"
                      end_time: "2023-07-14T09:05:00Z"
                    - transaction_id: 2
                      amount: 0.8
                      revenue: 1.6
                      start_time: "2023-07-14T10:00:00Z"
                      end_time: "2023-07-14T10:05:00Z"
                    - transaction_id: 3
                      amount: 0.6
                      revenue: 1.2
                      start_time: "2023-07-14T11:00:00Z"
                      end_time: "2023-07-14T11:02:00Z"
  api/statistics/{dispenser_id}:
    get:
      summary: Retrieve statistics for a dispenser
      parameters:
        - in: path
          name: dispenser_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Dispenser statistics
          content:
            application/json:
              example:
                dispenser_id: 2
                flow_volume: 5
                price: 2.1
                is_open: False
                total_transactions: 3
                total_amount: 2.1
                total_revenue: 3.85
                transactions:
                  - transaction_id: 1
                    amount: 0.7
                    revenue: 1.05
                    start_time: "2023-07-14T10:00:00Z"
                    end_time: "2023-07-14T10:10:00Z"
                  - transaction_id: 2
                    amount: 0.8
                    revenue: 1.6
                    start_time: "2023-07-14T11:00:00Z"
                    end_time: "2023-07-14T11:05:00Z"
                  - transaction_id: 3
                    amount: 0.6
                    revenue: 1.2
                    start_time: "2023-07-14T12:00:00Z"
                    end_time: "2023-07-14T12:02:00Z"
  /auth/login:
    post:
      summary: Authenticate a user and obtain a JWT token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Admin'
      responses:
        '200':
          description: JWT token obtained successfully
          content:
            application/json:
              example:
                access_token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
          
          
components:
  schemas:
    Dispenser:
      type: object
      properties:
        flow_volume:
          type: number
          format: float
        price:
          type: number
          format: float
      required:
        - flow_volume
        - price
    Admin:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - username
        - password
